FROM node:20-alpine AS build

WORKDIR /app

COPY front-end/package.json front-end/package-lock.json* ./
RUN npm install

COPY front-end/ .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
